CREATE TABLE `store_goods_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `store_no` varchar(10) NOT NULL COMMENT '门店编号',
  `goods_no` varchar(50) NOT NULL COMMENT '商品编号',
  `goods_id` bigint(20) NOT NULL,
  `region_code` varchar(50) NOT NULL,
  `is_orderable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可订货  0:不可订货；1:可订货',
  `is_returnable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可退货  0:不可退货；1:可退货',
  `is_saleable` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可销售  0:不可销售；1:可销售',
  `is_sub_sale_online` tinyint(1) DEFAULT '1' COMMENT '子商品是否线上可售 0：否 1：是',
  `is_variable_price` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可变价  0:不可变价；1:可变价',
  `is_purchase_recommend` tinyint(1) DEFAULT '0' COMMENT '是否采购推荐 0:否 1:是',
  `is_new` tinyint(1) DEFAULT '0' COMMENT '是否新品 0:否 1:是',
  `sale_channel` varchar(150) DEFAULT NULL COMMENT '销售渠道',
  `base_price` decimal(12,4) DEFAULT NULL COMMENT '配送基准价',
  `main_vendor_id` bigint(20) DEFAULT NULL,
  `vip_price` decimal(12,4) DEFAULT NULL COMMENT '默认会员价',
  `real_vip_price` decimal(12,4) DEFAULT NULL COMMENT '当前会员价',
  `promotion_no` varchar(20) DEFAULT NULL COMMENT '促销单号',
  `flag` int(10) DEFAULT NULL COMMENT '二进制标识，0初始值，2正在促销，4binlog不同步，8必定，16日清',
  `sale_tax_rate` varchar(50) NOT NULL COMMENT '销项税率',
  `settlement_method_code` varchar(20) DEFAULT NULL COMMENT '结算方式',
  `settlement_method_name` varchar(50) DEFAULT NULL COMMENT '结算方式值',
  `state` varchar(50) DEFAULT '0' COMMENT '二进制 0 初始 1 删除 2 可订货 4 可退货 8 是否可销售 16 是否可变价 64 是否季节性商品 128 是否线上销售 512 是否自营',
  `main_vendor_no` varchar(50) DEFAULT NULL,
  `real_sale_price` decimal(12,4) NOT NULL COMMENT '当前售价(当前售价默认等于默认售价)',
  `sale_price` decimal(12,4) NOT NULL COMMENT '默认售价',
  `create_time` datetime DEFAULT NULL COMMENT '该记录创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '该记录最后更新时间',
  `dis_rule_desc` varchar(1024) DEFAULT NULL COMMENT '活动文本',
  `sale_begin_date` datetime DEFAULT NULL COMMENT '促销开始时间',
  `sale_end_date` datetime DEFAULT NULL COMMENT '促销结束时间',
  `vip_begin_date` datetime DEFAULT NULL COMMENT 'VIP价格开始时间',
  `vip_end_date` datetime DEFAULT NULL COMMENT 'VIP价格结束时间',
  `price_change_date` datetime DEFAULT NULL COMMENT '价格变更日期',
  `dis_price` decimal(16,4) DEFAULT NULL COMMENT '折扣单价',
  `version` int(11) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `store_no_goods_no` (`store_no`,`goods_no`) USING BTREE,
  KEY `goods_no` (`goods_no`) USING BTREE,
  KEY `idx_sg_sg` (`store_no`,`goods_id`),
  KEY `idx_sg_rsg` (`region_code`,`store_no`,`goods_id`),
  KEY `idx_goodsno_storeno_regioncode` (`goods_no`,`store_no`,`region_code`)
) ENGINE=InnoDB AUTO_INCREMENT=23893484 DEFAULT CHARSET=utf8mb4 COMMENT='门店商品信息';

